version: "3"

services:
  app:
    volumes:
      - symfony_core_app-sync:/app
  web:
    ports:
      - 8080:80
      - 8081:443
    volumes:
      - symfony_core_app-sync:/app
  node:
    volumes:
      - symfony_core_app-sync:/app
  phpmyadmin:
    build:
      context: ..
      dockerfile: ./docker/services/phpmyadmin/Dockerfile
    depends_on:
      - database
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8082:80
  maildev:
    build:
      context: ..
      dockerfile: ./docker/services/maildev/Dockerfile
    ports:
      - 8083:80

volumes:
  symfony_core_app-sync:
    external: true
  symfony_core_web-sync:
    external: true
